#!/bin/bash
set -e

# Link:  https://tuhrig.de/how-to-know-you-are-inside-a-docker-container/
function isRunningInsideContainer() {
    awk -F/ '$2 == "docker"' /proc/self/cgroup >/dev/null 2>&1 | read
}

case $1 in

down)
    docker-compose down
    ;;

destroy)
    docker-compose down -v
    ;;

in)
    docker-compose exec wordpress /bin/bash
    ;;

logs)
    docker-compose logs
    ;;

composer)
    command="cd wp-content/plugins/custom-pixelex-aspect && composer ${@:2}"
    docker-compose run --rm wordpress /bin/bash -c "${command}"
    ;;

npm)
    command="cd wp-content/themes/custom && npm ${@:2}"
    docker-compose run --rm wordpress /bin/bash -c "${command}"
    ;;

npx)
    command="cd wp-content/themes/custom && npx ${@:2}"
    docker-compose run --rm wordpress /bin/bash -c "${command}"
    ;;

*)
    docker-compose up --build -d
    ;;

esac

exit 0
